import OpenAI from "openai";
import { execFile } from "child_process";
import { writeFile, unlink } from "fs/promises";
import { existsSync } from "fs";
import { randomUUID } from "crypto";
import { tmpdir } from "os";
import path from "path";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// Roughly 8000 characters (~2000 tokens) of source text. This is a
// deliberate cost/simplicity tradeoff: long documents get summarized
// from their first ~8000 characters only, not the whole thing. A more
// complete version would chunk the document and summarize-of-
// summaries; worth saying out loud if asked, not worth building for v1.
const MAX_INPUT_CHARS = 8000;

/**
 * Extracts text via poppler's `pdftotext` CLI rather than a PDF-parsing
 * npm library.
 *
 * Why: the obvious choice, the `pdf-parse` npm package, failed with a
 * "bad XRef entry" error on a perfectly valid test PDF generated by
 * PDFKit - confirmed valid by running `pdfinfo`/`pdftotext` on the same
 * file directly. Rather than ship a library with a known compatibility
 * gap, this shells out to `pdftotext`, which is actively maintained,
 * handles more real-world PDFs correctly, and is what a lot of
 * production PDF pipelines use under the hood anyway. The tradeoff:
 * the deployment target needs `poppler-utils` installed
 * (`apt install poppler-utils` - one line, see DEPLOYMENT.md).
 */
export async function extractPdfText(buffer: Buffer): Promise<string> {
  const tempPath = path.join(tmpdir(), `docvault-${randomUUID()}.pdf`);
  await writeFile(tempPath, buffer);

  let pdftotextCmd = "pdftotext";
  if (process.platform === "win32") {
    const chocoPath = "C:\\ProgramData\\chocolatey\\bin\\pdftotext.exe";
    if (existsSync(chocoPath)) {
      pdftotextCmd = chocoPath;
    }
  }

  try {
    const text = await new Promise<string>((resolve, reject) => {
      execFile(pdftotextCmd, [tempPath, "-"], (error, stdout) => {
        if (error) return reject(error);
        resolve(stdout);
      });
    });
    return text.trim();
  } catch (err: any) {
    if (process.env.NODE_ENV === "development" && (err.code === "ENOENT" || err.message?.includes("ENOENT"))) {
      console.warn("WARNING: pdftotext not found. Falling back to mock extracted text for development.");
      return "Mock extracted PDF text because poppler-utils (pdftotext) is not installed on this machine. To enable real text extraction, please install poppler-utils.";
    }
    throw err;
  } finally {
    await unlink(tempPath).catch(() => {});
  }
}

export async function summarizeText(text: string): Promise<string> {
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "sk-replace-me") {
    console.warn("WARNING: No OpenAI API key configured. Returning mock summary for development.");
    return "[MOCK SUMMARY] This is a mock AI summary generated because no OpenAI API key is configured. It outlines the primary points of the document based on its extracted text.";
  }

  const truncated = text.slice(0, MAX_INPUT_CHARS);

  const response = await openai.chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content:
          "You are a professional document analyst for a personal document vault app. " +
          "Produce a well-structured markdown summary of the given document text. Format:\n\n" +
          "# Document Summary\n\n" +
          "A 2-3 sentence high-level overview paragraph.\n\n" +
          "## Key Points\n\n" +
          "- Bullet point 1\n" +
          "- Bullet point 2\n" +
          "- Bullet point 3\n\n" +
          "## Details\n\n" +
          "A short paragraph with additional context, dates, figures, or actionable items found in the document.\n\n" +
          "Keep the total output under 300 words. Use markdown headings (#, ##), bold (**text**), and bullet points (-).",
      },
      { role: "user", content: truncated },
    ],
    temperature: 0.3,
    max_tokens: 600,
  });

  return response.choices[0]?.message?.content?.trim() || "";
}

export async function summarizeImage(buffer: Buffer, mimeType: string): Promise<string> {
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "sk-replace-me") {
    console.warn("WARNING: No OpenAI API key configured. Returning mock image summary for development.");
    return "# Image Summary\n\n" +
      "This is a mock AI summary generated for development. It outlines key visual sections of the document.\n\n" +
      "## Key Elements\n\n" +
      "- **Document Type**: Form / Invoice / Image\n" +
      "- **Mock Status**: Active\n" +
      "- **Notes**: Please add a valid OpenAI API key to see a real vision analysis of this image.\n\n" +
      "## Details\n\n" +
      "The system has successfully uploaded the image to storage. When a real API key is configured, " +
      "the vision model will parse text contents, structure, and visual markers in this space.";
  }

  const base64Image = buffer.toString("base64");
  const dataUrl = `data:${mimeType};base64,${base64Image}`;

  const response = await openai.chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content:
          "You are a professional image and document analyst for a personal document vault app. " +
          "Analyze the provided image and generate a structured markdown description and summary. Format:\n\n" +
          "# Image Summary\n\n" +
          "A 2-3 sentence overview of what the image shows (e.g. receipt, invoice, photo, diagram, screenshot) and its overall content.\n\n" +
          "## Key Elements\n\n" +
          "- Highlight 1 (e.g. text content, dates, pricing, or objects found)\n" +
          "- Highlight 2\n" +
          "- Highlight 3\n\n" +
          "## Details\n\n" +
          "A short paragraph detailing any visible text, values, metadata, or context.\n\n" +
          "Keep the total output under 300 words. Use markdown headings (#, ##), bold (**text**), and bullet points (-).",
      },
      {
        role: "user",
        content: [
          { type: "text", text: "Please summarize and extract information from this image." },
          { type: "image_url", image_url: { url: dataUrl } },
        ],
      },
    ],
    temperature: 0.3,
    max_tokens: 600,
  });

  return response.choices[0]?.message?.content?.trim() || "";
}

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export async function answerQuestion(
  filename: string,
  context: string,
  question: string,
  history: ChatMessage[]
): Promise<string> {
  if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "sk-replace-me") {
    console.warn("WARNING: No OpenAI API key configured. Returning mock response for chatbot.");
    return `[MOCK ANSWER] This is a mock AI response about "${filename}" since no OpenAI API key is configured.\n\n` +
      `You asked: **${question}**\n\n` +
      `To enable real conversational answers about the document, please set a valid \`OPENAI_API_KEY\` in your environment.`;
  }

  const messages = [
    {
      role: "system",
      content:
        `You are a helpful AI document assistant for DocVault. You help users find information, translate details, or answer queries about the document "${filename}".\n\n` +
        `Here is the extracted content or summary of the document for your reference:\n` +
        `--- START DOCUMENT ---\n${context.slice(0, 40000)}\n--- END DOCUMENT ---\n\n` +
        `Answer the user's questions truthfully, professionally, and concisely using the document content provided above. ` +
        `If the answer cannot be found or reasonably inferred from the document, say "I couldn't find that information in the document."`,
    },
    ...history.map((h) => ({ role: h.role, content: h.content })),
    { role: "user", content: question },
  ];

  const response = await openai.chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: messages as any,
    temperature: 0.4,
    max_tokens: 500,
  });

  return response.choices[0]?.message?.content?.trim() || "";
}


